version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-rag
    environment:
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_pass
      - POSTGRES_DB=rag_regulation
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
